# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-07 13:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devohack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='titleImage',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
